CREATE DATABASE BancoRicardo
GO

USE BancoRicardo
GO

CREATE TABLE Usuario(
	Id INT IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	DataCriacao DATETIME NOT NULL,
	Email VARCHAR(255) NULL,
	Senha Varchar(12) NOT NULL,

	CONSTRAINT PK_IdUsuario PRIMARY KEY(Id),
	CONSTRAINT UQ_Email UNIQUE (Email)
)
GO

CREATE TABLE Opcao(
	Id INT IDENTITY,
	Nome VARCHAR(100) NOT NULL,

	CONSTRAINT PK_IdOpcao PRIMARY KEY(Id)
)
GO

CREATE TABLE Logon(
	Id INT IDENTITY,
	IdUsuario INT NOT NULL,
	DataLogon DATETIME NOT NULL,
	Sucesso BIT NOT NULL,

	CONSTRAINT PK_IdLogon PRIMARY KEY(Id),
	CONSTRAINT FK_IdUsuario_Logon FOREIGN KEY (IdUsuario) REFERENCES Usuario(Id)
)
GO

CREATE TABLE OpcaoAcionada(
	Id INT IDENTITY,
	IdLogon INT NOT NULL,
	IdOpcao INT NOT NULL,
	InstanteLogon DATETIME NOT NULL,

	CONSTRAINT PK_IdOpcaoAcionada PRIMARY KEY(Id),
	CONSTRAINT FK_IdLogon_OpcaoAcionada FOREIGN KEY (IdLogon) REFERENCES Logon(Id),
	CONSTRAINT FK_Idopcao_OpcaoAcionada FOREIGN KEY (IdOpcao) REFERENCES Opcao(Id)
)
GO
