 CREATE DATABASE SistemaLogin;
 GO

 USE SistemaLogin;

 CREATE TABLE Usuario(
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	DataCriacao DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_IdUsuario PRIMARY KEY (Id),
	CONSTRAINT UQ_Email UNIQUE (Email)
 );
 GO

 CREATE TABLE Logon(
	Id INT IDENTITY,
	IdUsuario INT NOT NULL,
	DataLogon DATETIME DEFAULT GETDATE(),
	SucessoLogin BIT NOT NULL

	CONSTRAINT PK_IdLogon PRIMARY KEY (Id),
	CONSTRAINT FK_IdUsuario_Logon FOREIGN KEY (IdUsuario) REFERENCES Usuario (Id)
 );
 GO

 CREATE TABLE Opcao(
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL

	CONSTRAINT PK_IdOpcao PRIMARY KEY (Id)
 );
 GO

 CREATE TABLE OpcaoAcionada(
	Id INT IDENTITY,
	IdLogon INT NOT NULL,	
	DataAcionamento DATETIME DEFAULT GETDATE(),
	IdOpcao INT NOT NULL

	CONSTRAINT PK_IdOpcaoAcionada PRIMARY KEY (Id),
	CONSTRAINT FK_IdLogon_OpcaoAcionada FOREIGN KEY (IdLogon) REFERENCES Logon (Id),
	CONSTRAINT FK_IdOpcao_OpcaoAcionada FOREIGN KEY (IdOpcao) REFERENCES Opcao (Id)
 );
 GO
